name: Schemaspy
on:
  - workflow_dispatch
  - push

jobs:
  schemaspy:
    runs-on: ubuntu-20.04
    services:
      db:
        image:  mysql/mysql-server:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: classicmodels
          MYSQL_ROOT_PASSWORD: P@ssw0rd
          MYSQL_USER: root 
          MYSQL_PASSWORD: root
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Show Docker containers
        run: docker ps -a
      - name: Show databases
        run: mysql --protocol=tcp -h localhost -P 3306 -u root -proot -e "SHOW DATABASES"
      - uses: actions/checkout@v3
      - name: Run Migration
        uses: docker://flyway/flyway:9
        env:
          FLYWAY_URL: jdbc:mysql://db:3306/classicmodels?allowPublicKeyRetrieval=true&useSSL=false&passwordCharacterEncoding=UTF-8
          FLYWAY_USER: root
          FLYWAY_PASSWORD: root
          FLYWAY_LOCATIONS: filesystem:./ddl
        with:
          args: migrate
      - name: Show table 
        run: mysql --protocol=tcp -h localhost -P 3306 -u root -proot classicmodels -e "SHOW TABLES"
      - name: Create dist
        run: | 
          sudo mkdir $(pwd)/dist
          sudo chmod 777 $(pwd)/dist
      - name: Run SchemaSpy
        run: |
          docker run \
          --rm \
          --net=${{ job.container.network }} \
          -e TZ=Asia/Tokyo \
          -v ${{ github.workspace }}/dist:/output \
          -v $PWD/schemaspy.properties:/schemaspy.properties \
          schemaspy/schemaspy:latest \
          -vizjs
      - name: check
        run : ls ${{ github.workspace }}/dist
      - name: zip arcive
        uses: montudor/action-zip@v1
        with:
            args: zip -qq -r archive.zip dist
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: schemaspy-artifact
          path: archive.zip
  deploy:
    runs-on: ubuntu-20.04
    needs: schemaspy
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: schemaspy-artifact
          path: /var/tmp/
      - name: check
        run : ls /var/tmp/*.zip
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::121936954111:role/github-actions
          aws-region: ap-northeast-1
      - name: 
        run : aws s3 ls
