name: schemaspy_sample
on:
  - workflow_dispatch

jobs:
  run-mysql-8_0:
    runs-on: ubuntu-20.04
    services:
      db:
        image:  mysql/mysql-server:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: classicmodels
          MYSQL_ROOT_PASSWORD: P@ssw0rd
          MYSQL_USER: root 
          MYSQL_PASSWORD: root
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Show Docker containers
        run: docker ps -a
      - name: Show databases
        run: mysql --protocol=tcp -h localhost -P 3306 -u root -proot -e "SHOW DATABASES"
      - uses: actions/checkout@v2
      - uses: joshuaavalon/flyway-action@v3.0.0
        with:
          url: jdbc:mysql://db:3306/classicmodels?allowPublicKeyRetrieval=true&useSSL=false&passwordCharacterEncoding=UTF-8
          user: root
          password: root
          locations: filesystem:./ddl
      - name: Show table 
        run: mysql --protocol=tcp -h localhost -P 3306 -u root -proot classicmodels -e "SHOW TABLES"