name: schemaspy_sample
on:
  - workflow_dispatch
  - push

jobs:
  run-mysql-8_0:
    runs-on: ubuntu-20.04
    services:
      db:
        image:  mysql/mysql-server:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: classicmodels
          MYSQL_ROOT_PASSWORD: P@ssw0rd
          MYSQL_USER: root 
          MYSQL_PASSWORD: root
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Show Docker containers
        run: docker ps -a
      - name: Show databases
        run: mysql --protocol=tcp -h localhost -P 3306 -u root -proot -e "SHOW DATABASES"
      - uses: actions/checkout@v3
      - name: Run Migration
        uses: docker://flyway/flyway:9
        env:
          FLYWAY_URL: jdbc:mysql://db:3306/classicmodels?allowPublicKeyRetrieval=true&useSSL=false&passwordCharacterEncoding=UTF-8
          FLYWAY_USER: root
          FLYWAY_PASSWORD: root
          FLYWAY_LOCATIONS: filesystem:./ddl
        with:
          args: migrate
      - name: Show table 
        run: mysql --protocol=tcp -h localhost -P 3306 -u root -proot classicmodels -e "SHOW TABLES"
      - name: Create dist
        run: mkdir $(pwd)/dist
      # - name: schamespy
      #   uses: docker://schemaspy/schemaspy:latest
      #   with:
      #     #options: -v "/tmp:/output" -v "./schemaspy.properties:/schemaspy.properties"
      #     options: -v ${{ github.workspace }}/dist:/output
      #     args: -v ${{ github.workspace }}/dist:/output -vizjs 
      - name: schamespy
        uses: addnab/docker-run-action@v3
        with:
           image: schemaspy/schemaspy:latest
           options: -v ${{ github.workspace }}/dist:/output -t mysql -host localhost -port 3306 -db classicmodels -u root -p root -vizjs
      - name: check
        run : ls ${{ github.workspace }}/dist